Feature/game play
founders-programme-2/commons pull request #54
Opened 2019-04-21 12:23 UTC by hshahwan

relates #18 
- create two buttons 
- link the buttons with landing page until other layouts are ready.

2019-04-21 14:13 UTC, Oliversw commented
Are you waiting to merge this until everything else is connected or did you want us to review and merge now @hshahwan? Just wondering because of the 'in-progress' label.

In my recent pull request I have linked a lot of the pages so this will be nice to include soon!

2019-04-21 16:32 UTC, hshahwan commented
@Oliversw It's okay if you review and merge, I am just want to prepare right ages to connects with it
issue #19

2019-04-21 17:02 UTC, ali-7 requested changes
Doesn't needs to be statefull component, make it statless and add props as parameters to inherit the react routes history props, then u can use it. 

Also i've made a button component in my BannerFooter pr wait for it to be merged the use it instead

2019-04-21 21:06 UTC, hshahwan commented
@ali-7  I changed to a stateful component to be scalable in the future if we will create private user, it  will be easy to save the situation of the user if he login in or not,
but it's easy to change

2019-04-22 06:57 UTC, teenie-quaggard approved these changes
In terms of whether or not to make this a stateful component, I think we just keep it stateless until we expand in the future. But either way is fine with me, as you are right - it's easy to change.

2019-04-22 08:29 UTC, ali-7 requested changes

2019-04-22 08:29 UTC, ali-7 commented on client/src/Component/views/Play/index.js
> +  // eslint-disable-next-line react/prop-types
make TypeProp validation

2019-04-22 08:41 UTC, ali-7 approved these changes
good girl :joy:

2019-04-22 08:41 UTC, merged