Fix/refactor footer button
founders-programme-2/commons pull request #55
Opened 2019-04-21 14:11 UTC by Oliversw

- Refactored the footer so that the buttons are now links that work with react router
- Swapped placement of 'back' and 'next' buttons since client in the UK reads from left to right
- Added statements to make the 'review scenario' and 'next' buttons only load if the props are supplied (for methods page and select your play page)
- Changed footer to a functional component since it does not need state
- Added prop-type checking
- Changed the declaration of footer on existing pages to reflect the above changes and linked them together. Still missing some pieces though

2019-04-21 16:22 UTC, hshahwan approved these changes

2019-04-21 16:29 UTC, ali-7 requested changes

2019-04-21 16:29 UTC, ali-7 commented on client/src/Component/Common/Footer/index.js
> +  // const { nextLink, backLink, reviewScenario } = props;
remove this line

2019-04-21 16:29 UTC, ali-7 commented on client/src/Component/Common/Footer/index.js
> +        { nextLink && <NextButton as={Link} to={nextLink} type="button" />}
`{ nextLink` >>> `{nextLink` :)))))

2019-04-21 16:29 UTC, ali-7 commented on client/src/Component/views/Methods/index.js
> +      <Footer backLink="/play" nextLink="/" reviewScenario={true} />
`reviewScenario={true}`  when passed as `reviewScenario` only, it will be true

2019-04-21 16:52 UTC, ali-7 requested changes

2019-04-21 16:52 UTC, ali-7 commented on client/src/Component/views/Play/index.js
> +      <Footer backLink="/howto" nextLink={false} reviewScenario={false} />
`nextLink={false}`  >>> `nextLink={null}` or `nextLink=""` to be valid props.

2019-04-22 06:51 UTC, teenie-quaggard approved these changes

2019-04-22 09:58 UTC, hshahwan approved these changes

2019-04-22 10:33 UTC, ali-7 approved these changes
:+1:

2019-04-22 10:35 UTC, merged