Feature/instructions page
founders-programme-2/commons pull request #61
Opened 2019-04-22 11:09 UTC by ali-7

Instructions page

  * contains header
  * contains title
  * contains "Instructions" copy
  * contains "back" and "next" buttons in footer

relate #17

2019-04-22 11:49 UTC, hshahwan approved these changes

2019-04-22 12:13 UTC, teenie-quaggard requested changes
Looks good Ali! I would update the text font-family to open sans as that is what we are using for our p tags throughout. Depending on how legible it is in open sans, I might adjust the font just a little bit bigger. Up to you though!

2019-04-22 13:06 UTC, Oliversw approved these changes
👍 😄

2019-04-23 10:20 UTC, teenie-quaggard approved these changes

2019-04-23 10:27 UTC, merged