Feature/key terms
founders-programme-2/commons pull request #76
Opened 2019-04-25 10:59 UTC by hshahwan

relates #27 
- add header
- add content by mapping on keyterms.js and get the data.
- footer

2019-04-25 12:27 UTC, Oliversw requested changes

2019-04-25 12:27 UTC, Oliversw commented on client/src/Component/views/KeyTerms/index.js
>        <Footer />
We just need to include all of the props in this footer so that it displays properly and without the "Review Scenario" button.

Like in the About page:
``` <Footer backLink="/" nextLink="/howTo" reviewScenario={false} />```

2019-04-25 12:27 UTC, Oliversw commented on client/src/Component/views/Persona/index.js
> +import React from 'react';
Is this meant to be part of this PR?

2019-04-25 12:27 UTC, Oliversw commented on client/src/Component/views/YourScenario/index.js
> +import React from 'react';
Is this meant to be part of this PR? Maybe you branched off from your scenario/persona branch?

2019-04-25 12:27 UTC, Oliversw commented on client/src/fakeData/keyTerms.js
> +    img: 'https://i.imgur.com/wWqQXb9.png',
Do you think it might be worth finding another SVG and including that in the repo like the other images that we have? Might make things more consistent. Also I know that it's a tiny detail but it might be nice to find an image with colours that fit the overall design a  bit more - it looks good, but I kind of feel like the blue looks very different from the other images. Let me know what you think!

2019-04-25 12:32 UTC, Oliversw commented on client/src/fakeData/keyTerms.js
> +    img: 'https://i.imgur.com/wWqQXb9.png',
Kristina found a really nice example and is putting it in another comment!

2019-04-25 12:35 UTC, teenie-quaggard requested changes
Hi Haneen, thanks for working on this!

A few things...
1. when you map over the elements, each item should have a unique key property (react needs this). 

2. I would suggest choosing different icons for this page. (in h1 as well as each definition). In the rest of the app we use black outlined icons. It would probably be best to keep it consistent. The blue here also just seems a bit different in design to the look of our app. What do you think of this one? I uses the same yellow as we do :)
https://www.flaticon.com/free-icon/book_947509

3. Please capitalise all key terms (right now only Hub is capitalised)

4. Please put spaces between the periods in the definitions.

5. Please end each definition with a period.

Thank you!
🤩

2019-04-28 06:59 UTC, hshahwan commented on client/src/Component/views/KeyTerms/index.js
>        <Footer />
totally right, Thank @Oliversw

2019-04-28 07:01 UTC, hshahwan commented on client/src/Component/views/YourScenario/index.js
> +import React from 'react';
this weird, suppose not raise.

2019-04-28 14:44 UTC, teenie-quaggard requested changes
Hi Haneen! This is looking really great!! 👍

I just made a few very little requests regarding more to typos and sentence syntax.

2019-04-28 14:44 UTC, teenie-quaggard commented on client/src/Component/views/KeyTerms/index.js
> +import { WrapperTitlte, Img, Paragraph, Title } from './index.style';
Typo in WrapperTitle

2019-04-28 14:44 UTC, teenie-quaggard commented on client/src/Component/views/KeyTerms/index.js
> +            <WrapperTitlte>
Typo in WrapperTitle

2019-04-28 14:44 UTC, teenie-quaggard commented on client/src/Component/views/KeyTerms/index.js
> +            </WrapperTitlte>
Typo in WrapperTitle

2019-04-28 14:44 UTC, teenie-quaggard commented on client/src/fakeData/keyTerms.js
> +      'An organising group that may have access to a physical space that fosters communication and collaboration.An example might be a community center or a charity with an office.',
Needs space after period.

2019-04-28 14:44 UTC, teenie-quaggard commented on client/src/fakeData/keyTerms.js
> +      'A set of tools to help people work together - i.e. what we are trying to help people build by creating this web app.A hub may want to develop a platform, to increase communication in their com
Needs space after period.

2019-04-28 14:44 UTC, teenie-quaggard commented on client/src/fakeData/keyTerms.js
> +      'Groups of various organisations that work together for common causes.Often requires a membership.Network mapping makes these relationships visible and trackable.',
Needs space after period.

2019-04-28 18:11 UTC, ali-7 approved these changes

2019-04-29 09:52 UTC, teenie-quaggard commented
hi Haneen! I just added one last commit with some spaces after periods. Looks good to me!

2019-04-29 09:52 UTC, teenie-quaggard approved these changes

2019-04-29 09:53 UTC, merged